apiVersion: v1
kind: Secret
metadata:
    name: vfo-zds-loy
    labels:
        helm.sh/chart: vfo-zds-loy-1.1.0
        app.kubernetes.io/name: vfo-zds-loy
        app.kubernetes.io/instance: vfo-zds-loy
        app.kubernetes.io/version: 1.1.0
        app.kubernetes.io/managed-by: Helm
stringData:
    ELASTIC_APM_SECRET_TOKEN: ENC[AES256_GCM,data:nDBTBp3Tz7bqfUcCrbCCfg==,iv:NF3PNRUbnN2fyJJqt4BrMGAZ0E+yNjP4QfShpuBexfg=,tag:mclkvaEsA7TiZfvi/OP36w==,type:str]
    FLUENTD_ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:/6ZwkPdBSaLA6I38gt+LtQ==,iv:XHiBv5oSZuARbzQjlFgqoL0MzSt4hUOloIWFbbaQUhA=,tag:ejSykROavj8kTcmk/Un2PA==,type:str]
    JAVAX_NET_SSL_KEYSTORE_TYPE: ENC[AES256_GCM,data:4ScP,iv:hcKAv8q+bt3eBEI1PRQsIV6AxaTf1CKfHohAxj+JTf8=,tag:gpD2zItCA5ybf6yRp1OIaA==,type:str]
    loy.properties: ENC[AES256_GCM,data:FlvFXCue1pkM4aQSkd66JtYBys2ixW82nB8uXVWMbB7mtaSVTkHpFC7Xl02lYRBQO5T0R4umi/hjs7x/tAYesNTyMSVL/L6iH9s+cxWU7gJDz010g5MQsmWm2Jq9oOdOzBcIWaB2gsYb5NdW8U4x8daNj0HhWGfGUMTavj66+5yB50onrB0j0Uh1rBT3TEYOrspmrFYevFcFNyeNm9/74VGO5aeSpU7RSikXPMh1aaMqL/4mEsa0dmQE/nqEmv8tCO5uFOTtoMbqur/711GfEExj4DKDvgwrj7hkRQPKdjETfDQRBDhrNRb5evWbWSzmidrmYEY3KVorq/jpz5NMqfL3/OlgkISzaMSbvwQ7lZb5kMSiqKbLsBrbMbyjcRUNFoylLPn0j5Ple712z6KMPXm9gR2RomTXDdE473+ZOmn631DYqTod3PQHk9dm0cI2VTwoaS24n6XEXXA3evp/d52rDvRYnbaqWfchYB26Cyf3yLWDWj7I,iv:kPXdIJQamqV1t27a/CRP4cMsevH/dtcVGxMnTDTeeO4=,tag:A6+9YzlM2I7S0tOc6DfjHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1helqcqsh9464r8chnwc2fzj8uv7vr5ntnsft0tn45v2xtz0hpfwq98cmsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VXhSd2o4TElwS0I1NS8w
            S01sT2lhWEZiSzErUWMyeXdvOGdYOTVaMVFvCjZ3N0JvQ2RTUzM1cXpJZmM2RmMy
            aEpXeWs1anRpY0cwSitLc1VkdUhxVHMKLS0tIEVZZnNlVVp0TWJneXZuMWt0TEJt
            MkVCblJKVDkzY0dNN0UzaEtXeTJ0bEkKkSjNYp8NKBsXSPN3NZ99NxxhBGk328hv
            4OaE/dD5M68SiDYphg84Xwomd+GceHMUmGQQNOw7odRjr62NVe8SNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T12:02:43Z"
    mac: ENC[AES256_GCM,data:yHWKraxEK6QDRC1Fs1m3nUbF45MQwtZ9hhwcPvyqMHkFGxyH1PcXev3cIcbrt+4HvWqQ0HCL7xktSWOXa1SErVuZsgwLGRy5epr5bezDN5mtsGE0KrQ1oKagq6uonqsMP5E9mSO1LZ4K+qTit6UfSTnuKml6x4QGGuJArCeisVk=,iv:e2OHmhIJceXZwG6zGSCO3W4gWtxvVb0JYvZM/EmXOYg=,tag:/j+OWz6LO3zb1+7FrGapiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
